# SPDX-FileCopyrightText: 2022 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

resolver: lts-19.6

packages:
- .

extra-deps:
- git: https://github.com/bitmappergit/nyan-interpolation.git
  commit: 60fce24eb01cfb693d1def533bdaa0dad00f72e4
  subdirs:
   - full
   - core
